---
- name: Converge
  hosts: all
  tasks:
    - name: "Include daixijun.sysctl"
      include_role:
        name: "daixijun.sysctl"
    - name: "Include daixijun.redis"
      include_role:
        name: "daixijun.redis"
      vars:
        redis_sentinel: true
        redis_sentinel_monitor_name: master
        redis_sentinel_monitor_master: "{{ hostvars['sentinel1'].ansible_default_ipv4.address }}"
        redis_sentinel_monitor_port: 6379
        redis_sentinel_monitor_password: ""
