---
- name: Converge
  hosts: all
  tasks:
    - name: "Include daixijun.epel"
      include_role:
        name: "daixijun.epel"
      vars:
        epel_repo_replace: true

    - name: "Include daixijun.redis"
      include_role:
        name: "daixijun.redis"
      vars:
        redis_sentinel: true
        redis_sentinel_monitors:
          - name: master
            master: "{{ hostvars['sentinel1'].ansible_default_ipv4.address }}"
            port: 6379
            password: ""
