---
- name: Verify
  hosts: all
  tasks:
    - name: Watting for HA VIP state is listening
      wait_for:
        host: 172.17.0.10
        port: 6379
        state: started
        timeout: 10

    - name: Redis ping
      command: /usr/local/bin/redis-cli -h 172.17.0.10 -p 6379 ping
