---
sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - docker

before_script:
  - cd ../
  - mv daixijun/ansible-role-redis daixijun.redis

install:
  - pip install --user molecule docker

script:
  - molecule test
