---
dist: xenial
sudo: required
language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"

virtualenv:
  system_site_packages: true

env:
  global:
    - ROLE_NAME: redis
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-${ROLE_NAME} daixijun.${ROLE_NAME}
  - cd daixijun.${ROLE_NAME}

install:
  - pip install molecule docker

script:
  - molecule test
