---
dist: xenial
sudo: required
language: python
python: "3.7"
cache: pip

env:
  - SCENARIO_NAME=default
  - SCENARIO_NAME=sentinel

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-redis daixijun.redis
  - cd daixijun.redis

install:
  - pip install "molecule[lint,docker]"

script:
  - molecule test --scenario-name ${SCENARIO_NAME}

notifications:
  email: false
  webhooks:
    on_success: change
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
