---
sudo: required
language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
services:
  - docker

before_script:
  - cd ../
  - mv daixijun/ansible-role-redis daixijun.redis

install:
  - pip install --user molecule docker

script:
  - molecule test
