---
dist: xenial
sudo: required
language: python
branches:
  only:
    - master
python: '3.7'

# env:
#   - MOLECULE_DISTRO=centos7
#   - MOLECULE_DISTRO=centos6
#   # - MOLECULE_DISTRO=ubuntu1804
#   - MOLECULE_DISTRO=debian9

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-redis daixijun.redis
  - cd daixijun.redis

install:
  - pip install molecule docker
  - pip install --upgrade testinfra

script:
  - molecule test

notifications:
  email: false
  webhooks:
    on_success: change
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
