---
- name: Create redis data directory
  file:
    path: "{{ redis_data_dir }}/{{ redis_port }}"
    recurse: yes
    state: directory
    owner: redis
    group: redis

- name: Create redis configuration
  template:
    src: redis.conf.j2
    dest: /etc/redis/{{ redis_port }}.conf
    owner: redis
    group: redis
  notify:
    - restart redis

# 为了删除老版本遗留下来的配置文件
- name: Remove redis service for single instance
  file:
    path: /usr/lib/systemd/system/redis_{{ redis_port }}.service
    state: absent

- name: Force flush handlers
  meta: flush_handlers
