---
- name: Install dependencies
  yum:
    name: jemalloc,jemalloc-devel,gcc,gcc-c++,make
    state: present
  register: install_dependencies
  async: 300
  poll: 0
  changed_when: False

- name: Wait for dependencies install complete
  async_status:
    jid: "{{ install_dependencies.ansible_job_id }}"
  register: install_dependencies_status
  until: install_dependencies_status.finished
  # delay: 5
  retries: 300

- name: Create redis group
  group:
    name: redis
    state: present
    system: true

- name: Create redis user
  user:
    name: redis
    create_home: true
    home: /var/lib/redis
    group: redis
    shell: /sbin/nologin
    comment: Redis Server

- name: Check whether redis is already installed
  stat:
    path: /usr/local/bin/redis-server
  register: redis_stat

- name: Unarchive redis-{{ redis_version }}
  unarchive:
    src: "{{ redis_download_url }}"
    dest: /usr/local/src/
    remote_src: yes
    creates: /usr/local/src/redis-{{ redis_version }}
  when:
    - redis_upgrade or not redis_stat.stat.exists

- name: Compile && install
  shell: "make -j && make install"
  args:
    chdir: /usr/local/src/redis-{{ redis_version }}
    removes: /usr/local/src/redis-{{ redis_version }}
  when:
    - redis_upgrade or not redis_stat.stat.exists
  async: 1000
  poll: 0
  register: compile_and_install
  notify:
    - restart all redis

- name: Wait for compile/install complete
  async_status:
    jid: "{{ compile_and_install.ansible_job_id }}"
  register: compile_install_status
  until: compile_install_status.finished
  # delay: 5
  retries: 1000
  when:
    - compile_and_install is defined
    - compile_and_install is changed

- name: Copy redis-shutdown
  template:
    src: redis-shutdown.sh.j2
    dest: /usr/local/libexec/redis-shutdown
    owner: redis
    group: redis
    mode: 0644

- name: Ensure redis related directory exists
  file:
    path: '{{ item }}'
    state: directory
    owner: redis
    group: redis
  loop:
    - '{{ redis_data_dir }}'
    - /etc/redis
    - '{{ redis_log_dir }}'
    - /var/run/redis
