---
- name: Load redis package vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure epel repo is installed (RedHat)
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure redis is installed
  package:
    name: '{{ redis_package }}'
    state: present

- name: Create redis group
  group:
    name: redis
    state: present
    system: true

- name: Create redis user
  user:
    name: redis
    create_home: true
    home: /var/lib/redis
    group: redis
    shell: /sbin/nologin
    comment: Redis Server

- name: Ensure data && configuration directory exists
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
    owner: redis
    group: redis
  loop:
    - '{{ redis_data_dir }}'
    - /etc/redis
    - /var/log/redis
    - /var/run/redis

- name: Configure
  template:
    src: redis.conf.j2
    dest: /etc/redis/{{ redis_port }}.conf
    owner: redis
    group: redis
  notify:
    - restart redis

- name: startup for upstart
  template:
    src: redis.init.j2
    dest: /etc/init.d/redis_{{ redis_port }}
    mode: 0755
  when: ansible_service_mgr in ['upstart','sysvinit']

- name: startup for systemd
  template:
    src: redis.service.j2
    dest: /lib/systemd/system/redis_{{ redis_port }}.service
  when: ansible_service_mgr == 'systemd'
  notify:
    - daemon-reload
