---
- name: Prepare checks
  import_tasks: prepare.yml
  tags:
    - prepare
    - check

- name: Install Redis
  import_tasks: install.yml
  tags:
    - install

- name: Generate ssl Certificate
  include_tasks: tls.yml
  when:
    - redis_ssl|bool
  tags:
    - install
    - tls

- name: Configuration redis instance
  import_tasks: configure.yml
  tags:
    - config

- name: Configuration sentinel instance
  include_tasks: sentinel.yml
  when:
    - redis_sentinel|bool
  tags:
    - molecule-idempotence-notest
