---
- name: Prepare checks
  import_tasks: prepare.yml
  tags:
    - prepare
    - check

- name: Install Redis
  import_tasks: install.yml
  tags:
    - install

- name: Generate ssl Certificate
  include_tasks: tls.yml
  when:
    - redis_ssl_enable|bool
  tags:
    - install
    - tls

- name: Configuration redis instance
  import_tasks: configure.yml
  tags:
    - config

# 由于sentinel在运行中会重写配置文件，所以没法做到幂等性
- name: Configuration sentinel instance
  include_tasks: sentinel.yml
  when:
    - redis_sentinel|bool
