---
- name: Verify redis version if tls is enabled
  fail:
    msg: "redis_version must greater 6.0 if redis_ssl is True, got {{ redis_version }}"
  when:
    - redis_ssl | bool
    - redis_version is version('6.0', operator="<")
  delegate_to: localhost
  become: false
  run_once: true

- name: Disable Transparent Huge Pages (THP)
  shell: echo never > {{ item }}
  changed_when: False
  ignore_errors: True
  loop:
    - /sys/kernel/mm/transparent_hugepage/enabled
    - /sys/kernel/mm/transparent_hugepage/defrag

- name: Disable Transparent Huge Pages (THP) forever
  blockinfile:
    marker: "# {mark} Disable Transparent Huge Pages"
    block: |
      if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
      fi
      if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
        echo never > /sys/kernel/mm/transparent_hugepage/defrag
      fi
    path: /etc/rc.local
    state: present
