---
- name: Create sentinel data directory
  file:
    path: "{{ redis_data_dir }}/sentinel_{{ redis_sentinel_port }}/"
    recurse: yes
    state: directory
    owner: redis
    group: redis

- name: Gather services facts
  service_facts:
  no_log: yes

- name: Create sentinel configuration
  template:
    src: sentinel.conf.j2
    dest: /etc/redis/sentinel_{{ redis_sentinel_port }}.conf
    owner: redis
    group: redis
  notify:
    - restart sentinel
  vars:
    service_name: "sentinel@{{ redis_sentinel_port }}.service"

  # when:
  #   - "service_name not in ansible_facts.services or ansible_facts.services[service_name].state != 'running'"
- name: Create sentinel check master script
  template:
    src: sentinel_check_master.sh.j2
    dest: /etc/redis/sentinel_check_master.sh
    owner: redis
    group: redis
    mode: 0644

- name: Startup sentinel service for systemd
  template:
    src: sentinel.service.j2
    dest: /lib/systemd/system/sentinel@.service
  notify:
    - restart sentinel

- name: Force flush handlers
  meta: flush_handlers
