---
- name: Converge
  hosts: all
  tasks:
    - name: "Include daixijun.sysctl"
      include_role:
        name: "daixijun.sysctl"
    - name: "Include daixijun.redis"
      include_role:
        name: "daixijun.redis"
      vars:
        redis_version: 6.0.6
        redis_port: 6379
        redis_ssl: true
        redis_ssl_ca: ssl/{{ redis_port }}/ca.crt
        redis_ssl_cert: ssl/{{ redis_port }}/server.crt
        redis_ssl_key: ssl/{{ redis_port }}/server.key
        redis_ssl_dh: ssl/{{ redis_port }}/redis.dh
