---
- name: Verify
  hosts: all
  tasks:
    - name: Check redis instance port 6379 state is listening
      wait_for:
        host: 0.0.0.0
        port: 6379
        state: started
        timeout: 10

    - name: Try to connect to the redis instance
      command: >-
        /usr/local/bin/redis-cli \
          -a test \
          --tls \
          --cacert /etc/redis/ssl/6379/ca.crt \
          --cert /etc/redis/ssl/6379/redis.crt \
          --key /etc/redis/ssl/6379/redis.key \
          info replication
      register: replstatus
      no_log: True

    - name: Assert that master status
      assert:
        that:
          - replstatus.rc == 0
          - "'role:master' in replstatus.stdout_lines"
          - "'connected_slaves:{{ groups['slave'] | length }}' in replstatus.stdout_lines"
      when:
        - inventory_hostname not in groups['slave']

    - name: Assert that slave status
      assert:
        that:
          - replstatus.rc == 0
          - "'role:slave' in replstatus.stdout_lines"
          - "'master_link_status:up' in replstatus.stdout_lines"
      when:
        - inventory_hostname in groups['slave']
