---
- name: restart redis
  systemd:
    enabled: yes
    daemon_reload: yes
    name: redis@{{ redis_port }}.service
    state: restarted

- name: restart sentinel
  systemd:
    name: sentinel@{{ redis_sentinel_port }}.service
    enabled: yes
    daemon_reload: true
    state: restarted
