---
- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: restart redis instance {{ item.port }}
  service:
    enabled: yes
    name: redis_{{ item.port }}
    state: restarted
  when: item.changed
  loop: "{{ redis_notify_items }}"
  listen: restart redis

- name: restart all redis
  service:
    enabled: yes
    name: redis_{{ item.port }}
    state: restarted
  loop: "{{ redis_items | list }}"
  no_log: true
