---
- name: Converge
  hosts: all
  tasks:
    - name: "Include daixijun.redis"
      include_role:
        name: "daixijun.redis"
      vars:
        redis_version: 6.0-rc3
        redis_ssl: true
        redis_ssl_ca: ssl/{{ redis_port }}/ca.crt
        redis_ssl_cert: ssl/{{ redis_port }}/server.crt
        redis_ssl_key: ssl/{{ redis_port }}/server.key
        redis_sentinel: true
        redis_sentinel_monitor_name: master
        redis_sentinel_monitor_master: "{{ hostvars['sentinel1'].ansible_default_ipv4.address }}"
        redis_sentinel_monitor_port: 6379
        redis_sentinel_monitor_password: ""
        redis_sentinel_monitor_master_ssl: true
        redis_sentinel_monitor_master_ssl_ca: ssl/{{ redis_port }}/ca.crt
        redis_sentinel_monitor_master_ssl_cert: ssl/{{ redis_port }}/server.crt
        redis_sentinel_monitor_master_ssl_key: ssl/{{ redis_port }}/server.key

    - name: "Include daixijun.keepalived"
      include_role:
        name: "daixijun.keepalived"
      vars:
        keepalived_vrrp_scripts:
          - name: chk_redis
            script: "/usr/bin/bash /etc/redis/sentinel_check_master.sh 26379 master"
            weight: -10
        keepalived_vrrp_instances:
          - name: VI_REDIS
            state: BACKUP
            interface: eth0
            virtual_router_id: 50
            advert_int: 1
            track_script:
              - chk_redis
            authentication:
              type: PASS
              pass: 1111
            virtual_ipaddress:
              - 172.17.0.100/16
