---
- name: Verify
  hosts: all
  tasks:
    - name: Watting for HA VIP state is listening
      wait_for:
        host: 172.17.0.100
        port: 6379
        state: started
        timeout: 10

    - name: Redis ping
      command: >-
        /usr/local/bin/redis-cli \
          --tls \
          --cacert /etc/redis/ssl/6379/ca.crt \
          --cert /etc/redis/ssl/6379/redis.crt \
          --key /etc/redis/ssl/6379/redis.key \
          -h 172.17.0.100 \
          -p 6379 \
          ping
