---
- name: Converge
  hosts: all
  become: yes
  tasks:
    - name: Include daixijun.redis
      include_role:
        name: daixijun.redis
      vars:
        redis_version: 5.0.8
        redis_port: 6379
        redis_password: test
