---
- name: Converge
  hosts: all
  become: yes
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: daixijun.redis
      redis_version: 5.0.5
      redis_items:
        - port: 6379
          disabled_commands:
            - keys
            - flushall
          password: test
        - port: 6380
